# Generated by Django 3.0.5 on 2020-06-28 18:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('Desc', models.CharField(blank=True, max_length=100)),
                ('date_published', models.DateField(blank=True, default=datetime.date.today)),
                ('type', models.CharField(choices=[('E', 'Electric'), ('G', 'Games'), ('B', 'books'), ('O', 'Other')], max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', related_query_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['title', '-type'],
            },
        ),
    ]
