# Generated by Django 3.0.7 on 2020-06-30 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Img',
            field=models.ImageField(blank=True, upload_to='products/'),
        ),
    ]
