# Generated by Django 3.0.7 on 2020-07-10 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_comment_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='commnet',
            new_name='comment',
        ),
    ]
