# Generated by Django 3.0.5 on 2020-07-06 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0003_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Like_or_not', models.CharField(choices=[('L', 'LIKe'), ('D', 'Dislike')], max_length=1)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('commnet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='REPORT',
        ),
    ]
