# Generated by Django 3.0.5 on 2020-07-08 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_commentnew'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='report',
            field=models.ImageField(max_length=500, null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='CommentNEW',
        ),
    ]
