# Generated by Django 3.0.5 on 2020-07-08 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200708_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='report',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
