# Generated by Django 3.0.5 on 2020-07-08 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20200708_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='report',
        ),
    ]
