# Generated by Django 3.0.5 on 2020-07-13 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200710_1335'),
        ('products', '0010_report'),
    ]

    operations = [
    ]
