# Generated by Django 3.0.5 on 2020-07-13 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_merge_20200713_1538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='comment',
            new_name='commnet',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='comment',
            new_name='commnet',
        ),
    ]
